<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GEMRENE" name="RetryMultipleFailedTestCases" tests="5" failures="4" timestamp="21 May 2019 14:54:25 GMT" time="0.072" errors="0">
  <testcase name="Test1" time="0.022" classname="com.retryLogic.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.retryLogic.RetryTest.Test1(RetryTest.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="com.retryLogic.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.retryLogic.RetryTest.Test1(RetryTest.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="com.retryLogic.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.retryLogic.RetryTest.Test1(RetryTest.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="com.retryLogic.RetryTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.retryLogic.RetryTest.Test1(RetryTest.java:14)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.002" classname="com.retryLogic.RetryTest"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
